version: "3.8"

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - app-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
